function updateDocs(heading)
{
   theDocs.htmlText = this[heading];
}
function SelectAndClick(Help_list)
{
   updateDocs(Help_list.getSelectedItem().data);
   thecr.setScrollPosition(0);
   s;
}
this.swapDepths(6001);
theDocs.html = true;
my_email = "colm_mc2000@yahoo.com";
Help_list.addItem("Welcome","Welcome_doc");
Help_list.addItem("Open","Open_doc");
Help_list.addItem("Save","Save_doc");
Help_list.addItem("Text","Text_doc");
Help_list.addItem("Media","Media_doc");
Help_list.addItem("Draw","Draw_doc");
Help_list.addItem("Ruler","Ruler_doc");
Help_list.addItem("Background Color","BkColor_doc");
Help_list.addItem("Music","Music_doc");
Help_list.addItem("Insert Slide","Insert_doc");
Help_list.addItem("Remove Slide","Remove_doc");
Help_list.addItem("Copy/Move Slide","Move_doc");
Help_list.addItem("Rec>Previous","PrevRec_doc");
Help_list.addItem("Rec>Next","NextRec_doc");
Help_list.addItem("Play","Play_doc");
Help_list.addItem("Motion Tab","Motion_doc");
Help_list.addItem("Intelli-clips","intella_doc");
Help_list.addItem("Publish for the web","PubWeb_doc");
Help_list.addItem("Questions & Issues","Q_doc");
Help_list.setChangeHandler("SelectAndClick");
Help_list.setStyleProperty("background",12770484);
Welcome_doc = "Welcome to <b>FlashPoint</b><br><br>FlashPoint is an application that allows you to create Power Point-Like presentations in Flash.<br><br>Your presentations can include Text, Photos, Flash Video, or other Flash Media.<br><br>You can even add custom drawings, music and motion to your presentation.<br><br>FlashPoint allows you to save your presentations to playback locally on your computer, or you can post presentations to the web.<br><br>Select the items below for assistance.";
Open_doc = "<b>Open</b><br><br>Click on this button to open a saved presentation or to create a new presentation.";
Ruler_doc = "<b>Ruler</b><br><br>To add alignment to your media elements on stage:<br><br>1. Click the Ruler button. The Position Grid will appear.<br><br>2. Select the Align tab on the Media Palette of your element on the stage.<br><br>3. To align the \'\'X\'\' position (right to left), move the \'\'X\'\' scroll handle of the position grid to the desired position.<br><br>4.  Click the \'\'Align Left\'\' button in the Media Palette. .<br><br>5. To align the \'\'Y\'\' position (Up and Down), move the \'\'Y\'\' scroll handle of the position grid to the desired position.<br><br>4.  Click the \'\'Align Top\'\' button in the Media Palette.<br><br><b>Note:</b> If you are authoring content for Mini-FlashPoint, but not using FlashPointMini.exe, use the center grid line as an indication of the bottom of your presentation.";
BkColor_doc = "<b>Background Color</b><br><br>To change the Background color of your presentation:<br><br>1.  Click on the Bk Color button. The Color Palette window will appear.<br><br>2.  Add color by selecting colors from the color menu, or by inputting the hexadecimal color value and clicking the submit button.";
Music_doc = "<b>Music</b><br><br>To add music to you presentation:<br><br>1. Click on the Music button. The Music window will appear.<br><br>2. Enter the path (locally or http://) to the music (.mp3) and click load. The window will indicate when the song is 100% loaded.<br><br>3. To test the song, click the \'\'Song Preview\'\' button.<br><br>4. To stop the song click the \'\'Song Preview\'\' button again.<br><br>5. When you are in Play mode, you can toggle the music on or off by clicking the sound button in the mini controller.<br><br><b>Tip</b><br><br>It is a good idea to place all of the media, used in your presentation, in a folder in the same directory as your FlashPoint application.<br><br><b>Note:</b> If you wish to use additional music in your presentation, or if you wish to have audio clips on different slides, use the Intelli-clips mp3 player.";
NextRec_doc = "<b>Record and Next</b><br><br>This button will record the current page and advance to a new page.<br><br>Your presentation can have as many pages as you want.<br><br><b>Note:</b><br><br>Please keep in mind that once you record a page, the positions of your media elements are now locked. If you wish to edit the positions, go to the \'\'Motion Tab\'\' and click the \'\'Reset\'\' button.";
Play_doc = "<b>Play Mode</b><br><br>There are two modes in FlashPoint, Edit mode and Presentation Mode.<br><br>The Play mode button will play back your presentation.<br><br>To enter Edit mode, while you are in Play mode, click the \'\'e\'\' button in the mini controller.<br><br>While in Play mode, you can also use the arrow keys on your keyboard to progress through the slides";
Save_doc = "<b>Save</b><br><br>The \'\'Save\'\' button will bring up the Save Window.<br><br>To save your presentation:<br><br>1.  Enter the name of your new presentation.<br><br><b>Tip</b><br><br>Please make sure there are no spaces in the name. If the name has spaces, you may have problems loading your presentation if you post it to the web.<br><br>2.  If you wish for your presentation to automatically start when FlashPoint is launched, click the Auto Start checkbox.<br><br>3.  If you wish for your presentation to automatically play and cycle through at certain intervals when FlashPoint is launched, click the Auto Run checkbox and enter the number of seconds for the interval. <br>(See \'\'Publish for the web\'\')<br><br>4.  Click the \'\'Save\'\' button. A small application will launch and save your presentation.";
Text_doc = "<b>Text</b><br><br>To add text to your presentation:<br><br>1. Click on the Text button. A marker will appear on the end of the cursor.<br><br>2. Place the cursor on the stage where you want text to appear.<br><br>3. Click the marker.<br><br>4. A Text Palette edit window and temporary text will appear.<br><br>5. Select the text \'\'Type Here \'\' and add your new text.<br><br>6. You can add formatting and color to your text and re-position your text by using the handle in the Text Palette edit window.<br><br>7. To add alignment or motion to your text click on the text palette.";
Media_doc = "<b>Media</b><br><br>To add photos (.jpg) or other Flash media (.swf) to your presentation:<br><br>1. Click on the Media button. A marker will appear on the end of the cursor.<br><br>2. Place the cursor on the stage where you want the media to appear.<br><br>3. Click the marker.<br><br>4. A Media Palette edit window and temporary media holder will appear.<br><br>5. Enter that path (locally or http://) and click load.<br><br>6. You can re-position your media by using the handle in the Media Palette edit window.<br><br><b>Tip</b><br><br>It is a good idea to place all of the media, used in your presentation, in a folder in the same directory as your FlashPoint application.";
Draw_doc = "<b>Draw</b><br><br>The drawing tool can create custom shapes and simple circles.<br><br>To add custom drawings to your presentation:<br><br>1. Click on the Draw button. A marker will appear on the end of the cursor.<br><br>2. Place the cursor on the stage where you want the drawing to appear.<br><br>3. Click the marker.<br><br>4.  A Drawing Palette edit window and a smaller Dot Maker window will appear.<br><br>5. To draw a shape, move the Dot Maker to different positions on stage and click \'\'make dot\'\'. When you have completed your shape click the \'\'connect\'\' button on the Dot Maker window to make an outline.<br><br>6. You can add color by selecting colors from the color menu on the Drawing Palette, or by inputting the hexadecimal color value and clicking the submit button.<br><br>7. To draw a simple circle, repeat steps 1-4, then select the \'\'circle\'\' button on the Drawing Palette, and use the Dot Maker to create a dot on stage, the first dot is the center point of the circle. Use the Dot Maker to create another point to mark the outer edge of your circle. These two dots will create a radius of your circle.<br><br>8.  Use the \'\'connect\'\' button on the Dot Maker to create an outline of your circle.<br><br>9.  You can add color by selecting colors from the color menu on the Drawing Palette, or by inputting the hexadecimal color value and clicking the submit button.<br><br>10. You can re-position your media by using the handle in the Media Palette edit window.<br><br><b>Tip</b><br><br>Use the ruler as a guide to make shapes more exact.";
PrevRec_doc = "<b>Record and Previous</b><br><br>This button will record the current page and go back to the prior page.<br><br><b>Note:</b><br><br>Please keep in mind that once you record a page, the positions of your media elements are now locked. If you wish to edit the positions, go to the \'\'Motion Tab\'\' and click the \'\'Reset\'\' button.";
Motion_doc = "<b>Motion Tab</b><br><br>You can enhance your presentation by adding motion effects, to each media element, on every page.<br><br>To add motion to your media elements:<br><br>1. Select the \'\'Motion\'\' tab of your media element.<br><br>2. Position the media element where you wish to start your animation, by moving the Media Palette anywhere on stage.<br><br>3.  Select the \'\'Lock\'\' button next to the \'\'Start\'\' text. This will lock the start position.<br><br>4.  Position the media element where you wish to end your animation, by moving the Media Palette anywhere on stage.<br><br>5.  Select the \'\'Lock\'\' button next to the \'\'End\'\' text. This will lock the end position.<br><br>6. To control the speed of your animation select the Speed radio button:<br><b>S</b>- Slow<br><b>M</b>- Medium<br><b>F</b>- Fast<br><br>7. To Preview your animation in \'\'Edit\'\' mode, click the \'\'Preview\'\' button.<br><br>8. Use the \'\'Reset\'\' button to unlock the \'\'Start\'\' and \'\'End\'\' position values.<br><br><b><u>Note:</u></b><br><br>After a page has been saved, you must use the \'\'Reset\'\' button if you plan on repositioning the media element.<br><br>After loading a saved page, the Palette edit window will appear in the end position on the motion trail.  Sometimes the end position is off stage. To edit the motion trail, you will have to reduce the height of the FlashPoint movie by grabbing the right left end and moving it to the top right end. You should be able to see your media element. Drag the element to the center of the stage and bring your movie back to normal size, then edit your motion trail. <br><br><b>Tip</b><br><br>To make your elements slide in from off stage select the end point first then lock the position. Then add a \'\'-\'\' to the start point \'\'X\'\' field and lock the \'\'Start\'\' position. Also, you can manually edit the filed number coordinates.";
PubWeb_doc = "<b>Publish for the web</b><br><br>Presentations can be posted on the web using FlashPoint.swf movie:<br><br>1.Copy ‘’FlashPoint.html’’ and ‘’FlashPoint.swf’’ from the ‘’Playback’’ folder up one folder so both appear in the same folder as FlashPoint.exe.<br><br>2. If you created a presentation for the mini-player, follow the same steps but use the \'\'FlashPointMini.html\'\' and <br>‘’FlashPointMini.swf’’<br><br>3. Copy the entire FlashPoint directly to your web server and link the html page.<br><br><b>Note:</b> If you want your presentation to automatically start, remember to select \'\'Auto Start\'\' when saving the movie. <br><br>If you wish for your presentation to automatically play and cycle through at certain intervals when FlashPoint is launched, click the Auto Run checkbox and enter the number of seconds for the interval.";
Q_doc = "<b>Questions?<br>Comments?<br>Issues?</b><br>Let me know.<br>Send me an email.<br><br><Font Color=\"#003063\"><a href=\"mailto:" + my_email + "?Subject=FlashPoint Feedback\"><b>Colm McKeon</b></a></Font>";
Insert_doc = "<b>Insert Slide</b><br><br>If you wish to insert a new slide into your presentation: <br><br>1. Navigate to the page where you wish to insert a slide. <br><br>2. Click the button.";
Remove_doc = "<b>Remove Slide</b><br><br>If you wish to remove a slide from your presentation: <br><br>1. Navigate to the page where you wish to delete a slide. <br><br>2. Click the button.";
Move_doc = "<b>Copy/Move Slide</b><br><br>If you wish to copy or move a slide to another page in your presentation: <br><br>1. Navigate to the slide you wish to copy or move.<br><br>2. Click the button. <br><br>3.  A dialog box will ask to where you wish to insert your moved or copied slide. <br><br>4. Click the button.<br><br><b>Tip:</b> If you wish to copy or move a slide to the end of your presentation, the \'\'Before’’ number should be one digit more than your last presentation slide number.";
intella_doc = "<b>Intelli-clips</b><br><br>These movie clips allow you to playback mp3\'s or Flash video,.flv.<br><br>These clips can even search FlashPoints \'\'flv\'\' or \'\'mp3\'\' directory\'s and automatically create a play list, and playback all of your Flash videos and mp3’s.<br><br>1. Use the Media Palette click on the \'\'Video\'\' or \'\'Sound\'\' button. <br><br>2. Follow the instructions on screen. You only need to do this once, the media information will be saved for playback later.<br><br><b>Tip:</b> As always, if you plan on posting your presentation to the web, remember to move the entire flv or mp3 directory\'s with your presentation.";
